# Generated by Django 3.0.6 on 2020-05-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2020)),
                ('month', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
                ('domain', models.CharField(max_length=255)),
                ('details', models.TextField()),
            ],
        ),
    ]
